name: 'Delete CED environment'
description: 'Github Action to delete an environment in CloudEdgeDistribution'
inputs:
  cli-token:
    description: "CloudEdgeDistribution CLI token. If not specified it'll try to resolve the CLI token from environment variable CED_CLI_TOKEN."
    required: false
  project-id:
    description: "Project id from CloudEdgeDistribution. If not specified it'll try to resolve it from environment variable `CED_PROJECT_ID`."
    required: false
  environment:
    description: "Environment to delete in CloudEdgeDistribution. If not specified it'll try to resolve it from environment variable CED_ENVIRONMENT."
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
