name: 'Delete CED environment'
description: 'Github Action to delete an environment in CloudEdgeDistribution'
inputs:
  cli-token:
    description: "CloudEdgeDistribution CLI token. If not specified it'll try to resolve the CLI token from environment variable CED_CLI_TOKEN."
    required: false
  environment:
    description: "Environment to delete in CloudEdgeDistribution. If not specified it'll try to resolve it from environment variable CED_ENVIRONMENT."
    required: false
  path:
    description: "Path to the CloudEdgeDistribution project. If not specified it'll try to resolve it from environment variable CED_PROJECT_PATH, it'll use current folder otherwise."
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
